/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasIndexRouteImport } from './routes/atlas/index'
import { Route as DevTanstack_librariesRouteImport } from './routes/dev/tanstack_libraries'
import { Route as DevDesignSystemRouteImport } from './routes/dev/design-system'
import { Route as AtlasOnboardingRouteImport } from './routes/atlas/onboarding'
import { Route as AtlasInboxRouteImport } from './routes/atlas/inbox'

const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIndexRoute = AtlasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtlasRoute,
} as any)
const DevTanstack_librariesRoute = DevTanstack_librariesRouteImport.update({
  id: '/dev/tanstack_libraries',
  path: '/dev/tanstack_libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasOnboardingRoute = AtlasOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasInboxRoute = AtlasInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AtlasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/atlas/inbox': typeof AtlasInboxRoute
  '/atlas/onboarding': typeof AtlasOnboardingRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
  '/atlas/': typeof AtlasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas/inbox': typeof AtlasInboxRoute
  '/atlas/onboarding': typeof AtlasOnboardingRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
  '/atlas': typeof AtlasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/atlas/inbox': typeof AtlasInboxRoute
  '/atlas/onboarding': typeof AtlasOnboardingRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
  '/atlas/': typeof AtlasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/atlas/inbox'
    | '/atlas/onboarding'
    | '/dev/design-system'
    | '/dev/tanstack_libraries'
    | '/atlas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas/inbox'
    | '/atlas/onboarding'
    | '/dev/design-system'
    | '/dev/tanstack_libraries'
    | '/atlas'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/atlas/inbox'
    | '/atlas/onboarding'
    | '/dev/design-system'
    | '/dev/tanstack_libraries'
    | '/atlas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRouteWithChildren
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  DevTanstack_librariesRoute: typeof DevTanstack_librariesRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/': {
      id: '/atlas/'
      path: '/'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AtlasIndexRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/dev/tanstack_libraries': {
      id: '/dev/tanstack_libraries'
      path: '/dev/tanstack_libraries'
      fullPath: '/dev/tanstack_libraries'
      preLoaderRoute: typeof DevTanstack_librariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/onboarding': {
      id: '/atlas/onboarding'
      path: '/onboarding'
      fullPath: '/atlas/onboarding'
      preLoaderRoute: typeof AtlasOnboardingRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/inbox': {
      id: '/atlas/inbox'
      path: '/inbox'
      fullPath: '/atlas/inbox'
      preLoaderRoute: typeof AtlasInboxRouteImport
      parentRoute: typeof AtlasRoute
    }
  }
}

interface AtlasRouteChildren {
  AtlasInboxRoute: typeof AtlasInboxRoute
  AtlasOnboardingRoute: typeof AtlasOnboardingRoute
  AtlasIndexRoute: typeof AtlasIndexRoute
}

const AtlasRouteChildren: AtlasRouteChildren = {
  AtlasInboxRoute: AtlasInboxRoute,
  AtlasOnboardingRoute: AtlasOnboardingRoute,
  AtlasIndexRoute: AtlasIndexRoute,
}

const AtlasRouteWithChildren = AtlasRoute._addFileChildren(AtlasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRouteWithChildren,
  DevDesignSystemRoute: DevDesignSystemRoute,
  DevTanstack_librariesRoute: DevTanstack_librariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
