/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTanstack_librariesRouteImport } from './routes/dev/tanstack_libraries'
import { Route as DevDesignSystemRouteImport } from './routes/dev/design-system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTanstack_librariesRoute = DevTanstack_librariesRouteImport.update({
  id: '/dev/tanstack_libraries',
  path: '/dev/tanstack_libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/dev/tanstack_libraries': typeof DevTanstack_librariesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/design-system' | '/dev/tanstack_libraries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/design-system' | '/dev/tanstack_libraries'
  id: '__root__' | '/' | '/dev/design-system' | '/dev/tanstack_libraries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  DevTanstack_librariesRoute: typeof DevTanstack_librariesRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tanstack_libraries': {
      id: '/dev/tanstack_libraries'
      path: '/dev/tanstack_libraries'
      fullPath: '/dev/tanstack_libraries'
      preLoaderRoute: typeof DevTanstack_librariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevDesignSystemRoute: DevDesignSystemRoute,
  DevTanstack_librariesRoute: DevTanstack_librariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
