/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTanstackLibrariesRouteImport } from './routes/dev/tanstack-libraries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTanstackLibrariesRoute = DevTanstackLibrariesRouteImport.update({
  id: '/dev/tanstack-libraries',
  path: '/dev/tanstack-libraries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/tanstack-libraries': typeof DevTanstackLibrariesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/tanstack-libraries': typeof DevTanstackLibrariesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/tanstack-libraries': typeof DevTanstackLibrariesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/tanstack-libraries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/tanstack-libraries'
  id: '__root__' | '/' | '/dev/tanstack-libraries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevTanstackLibrariesRoute: typeof DevTanstackLibrariesRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tanstack-libraries': {
      id: '/dev/tanstack-libraries'
      path: '/dev/tanstack-libraries'
      fullPath: '/dev/tanstack-libraries'
      preLoaderRoute: typeof DevTanstackLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevTanstackLibrariesRoute: DevTanstackLibrariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
