/**
 * Atlas domain: Thread Embedding
 *
 * `thread_embedding` stores revision-aware vector embeddings for threads,
 * suitable for semantic search and compatible with libSQL vector indexing.
 *
 * ── Revision awareness ───────────────────────────────────────────────────────
 *
 *   Each embedding row references the specific `thread_revision` from which
 *   it was computed.  When a new revision is created (effective content
 *   changes), a new embedding row is generated for that revision.  Old
 *   embedding rows are retained for audit purposes but the latest revision's
 *   embedding is used for search.
 *
 * ── libSQL vector storage ────────────────────────────────────────────────────
 *
 *   libSQL supports vector storage via the `F32_BLOB(N)` column type, where N
 *   is the embedding dimension.  Drizzle ORM does not have a first-class
 *   `f32blob` column type, so the embedding is stored as a `blob` column and
 *   the application is responsible for encoding/decoding the Float32Array.
 *
 *   The `embedding_dimension` column records the dimension at insert time so
 *   the application can validate the vector size on read.
 *
 *   The `embedding_model` column records the model used to generate the
 *   embedding (e.g. "text-embedding-3-small") so that embeddings from
 *   different models can be distinguished and re-generated if the model
 *   changes.
 *
 * ── Vector index DDL ─────────────────────────────────────────────────────────
 *
 *   libSQL vector indexes use the following DDL syntax (libSQL >= 0.4):
 *
 *     CREATE INDEX thread_embedding_vector_idx
 *       ON thread_embedding (libsql_vector_idx(embedding));
 *
 *   This DDL is NOT generated by Drizzle Kit because Drizzle does not yet
 *   support libSQL vector index syntax.  The planned migration DDL is
 *   documented here and must be applied manually or via a raw SQL migration
 *   when the libSQL runtime version supports it.
 *
 *   If the installed libSQL runtime does not support vector index DDL, the
 *   embedding table is still shipped in this migration and the vector index
 *   is deferred to a follow-up migration.
 *
 * ── Search exclusion ─────────────────────────────────────────────────────────
 *
 *   The `is_search_excluded` flag allows hidden rejected and trashed threads
 *   to be excluded from normal semantic search without deleting their
 *   embeddings.  Application code should filter on this flag when building
 *   search queries.
 */
import { relations, sql } from "drizzle-orm";
import {
	blob,
	index,
	integer,
	sqliteTable,
	text,
	uniqueIndex,
} from "drizzle-orm/sqlite-core";

import { thread } from "./thread.ts";
import { threadRevision } from "./revision.ts";

// ---------------------------------------------------------------------------
// thread_embedding
// ---------------------------------------------------------------------------

export const threadEmbedding = sqliteTable(
	"thread_embedding",
	{
		id: text("id").primaryKey(),

		// Parent thread.
		threadId: text("thread_id")
			.notNull()
			.references(() => thread.id, { onDelete: "cascade" }),

		// Source revision — the revision this embedding was computed from.
		threadRevisionId: text("thread_revision_id")
			.notNull()
			.references(() => threadRevision.id, { onDelete: "cascade" }),

		// -----------------------------------------------------------------------
		// Vector storage
		// -----------------------------------------------------------------------
		// The embedding vector stored as a raw binary blob (Float32Array).
		// libSQL stores this as F32_BLOB(N) at the storage layer.
		// The application encodes/decodes the Float32Array.
		embedding: blob("embedding", { mode: "buffer" }).notNull(),

		// Dimension of the embedding vector (e.g. 1536 for text-embedding-3-small).
		// Stored for validation and to support multi-model setups.
		embeddingDimension: integer("embedding_dimension").notNull(),

		// Model used to generate this embedding.
		embeddingModel: text("embedding_model").notNull(),

		// -----------------------------------------------------------------------
		// Search exclusion flag
		// -----------------------------------------------------------------------
		// Set to true for hidden rejected and trashed threads so they can be
		// excluded from normal semantic search without deleting their embeddings.
		isSearchExcluded: integer("is_search_excluded", { mode: "boolean" })
			.notNull()
			.default(false),

		// Timestamps.
		createdAt: integer("created_at", { mode: "timestamp_ms" })
			.default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
			.notNull(),
	},
	(table) => [
		// At most one embedding per (thread, revision, model).
		// This allows multiple models to coexist for the same revision.
		uniqueIndex("thread_embedding_thread_revision_model_unique").on(
			table.threadId,
			table.threadRevisionId,
			table.embeddingModel,
		),

		// All embeddings for a thread.
		index("thread_embedding_thread_id_idx").on(table.threadId),

		// Embeddings by revision (for latest-revision lookup).
		index("thread_embedding_revision_id_idx").on(table.threadRevisionId),

		// Search exclusion filter (for semantic search queries).
		index("thread_embedding_search_excluded_idx").on(table.isSearchExcluded),

		// -----------------------------------------------------------------------
		// PLANNED VECTOR INDEX (deferred — requires libSQL >= 0.4 runtime)
		// -----------------------------------------------------------------------
		// The following DDL creates a libSQL vector index on the embedding column.
		// It cannot be expressed in Drizzle Kit schema syntax and must be applied
		// via a raw SQL migration when the runtime supports it:
		//
		//   CREATE INDEX thread_embedding_vector_idx
		//     ON thread_embedding (libsql_vector_idx(embedding));
		//
		// Until this index is created, semantic search falls back to full-table
		// scan with application-side cosine similarity.
		// -----------------------------------------------------------------------
	],
);

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const threadEmbeddingRelations = relations(
	threadEmbedding,
	({ one }) => ({
		thread: one(thread, {
			fields: [threadEmbedding.threadId],
			references: [thread.id],
		}),
		threadRevision: one(threadRevision, {
			fields: [threadEmbedding.threadRevisionId],
			references: [threadRevision.id],
		}),
	}),
);
